export const timeline = [
  {
    company: "Freelance",
    title: "UI/UX Designer / Frontend Developer",
    date: "2024 - Present",
    description: "Building the future of web",
    responsibilities: [
      "Designed and developed user-friendly interfaces for websites and web applications",
      "Created wireframes, mockups, and prototypes to visualize design concepts",
      "Optimized website performance and ensured cross-browser compatibility",
      "Implemented responsive design principles to create mobile-friendly interfaces",
      "Utilized HTML, CSS, and JavaScript to build interactive and dynamic web experiences",
      "Stayed up-to-date with the latest design trends and best practices in web development",
    ],
  },
  {
    company: "Accent Media Agency",
    title: "Graphic Designer",
    date: "2022 - 2023",
    description: "Designed Attention grabbing designs",
    responsibilities: [
      "Designed visually appealing graphics, logos, and branding materials",
      "Developed and refined design concepts through sketches, wireframes, and mockups",
      "Created high-quality visual assets for print and digital media",
      "Applied color theory and typography principles to enhance visual communication",
      "Utilized Adobe Creative Suite to craft engaging and effective designs",
      "Remained current with the latest design trends and technologies in graphic design",
    ],
  },
  // {
  //   company: "Facebook",
  //   title: "Senior Software Engineer",
  //   date: "2020 - 2021",
  //   description: "Building the future of social networking",
  //   responsibilities: [
  //     "Developed a new feature that improves the user experience",
  //     "Implemented a recommendation algorithm to suggest friends",
  //     "Enhanced the news feed algorithm to show more relevant posts",
  //     "Built a feature for tracking user activity",
  //   ],
  // },
  // {
  //   company: "Apple",
  //   title: "Senior Software Engineer",
  //   date: "2019 - 2020",
  //   description: "Building the future of technology",
  //   responsibilities: [
  //     "Improved the iOS operating system to enhance user experience",
  //     "Developed a new feature that personalizes user interface",
  //     "Enhanced the app store algorithm to suggest more relevant apps",
  //     "Implemented a feature for tracking app usage",
  //   ],
  // },
  // {
  //   company: "Microsoft",
  //   title: "Senior Software Engineer",
  //   date: "2018 - 2019",
  //   description: "Building the future of software",
  //   responsibilities: [
  //     "Improved the Windows operating system to enhance user experience",
  //     "Developed a new feature that personalizes user interface",
  //     "Enhanced the office suite to improve productivity",
  //     "Implemented a feature for tracking software usage",
  //   ],
  // },
];
